title: " "
description: " "

# however youâ€™re activating the theme; either of these is fine:

markdown: kramdown

kramdown:
  syntax_highlighter: rouge

# If GitHub wrote this for you:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# OR if youâ€™re using the plain theme line instead:
# theme: jekyll-theme-minimal

baseurl: "/AdSlicerProXP-docs"
exclude:
  - README.md
  - LICENSE
  - .git
  - .github
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

logo: "/assets/img/logo.png"  # ðŸ‘ˆ THIS is the important line
show_downloads: false     # optional, hides the ZIP/TAR buttons

permalink: pretty

collections:
  docs:
    output: true
    permalink: /:path/
    
include:
  - assets/css/custom.css
